### ISSUE TITLE
What about MD shadows?

### ISSUE THREAD

**Issue by GriNAME** [BrunnerLivio/vscode-material-snippets#3]
What do you think about MD shadows? I can add it. Smth like this [shadows ](https://github.com/gmdjs/gmdjs/blob/material/assets/sass/material/mixins/_shadow.sass)

**Comment by BrunnerLivio** [comment]
Seems like a great idea! 
I'm fine with the box shadows of your linked file, but is it Material Design standart? Otherwise I suggest  MaterializeCSS or AngularMaterials box shadow styling, which is probably Material Design standart. 

Do you want to implement this or shall I?

**Comment by GriNAME** [comment]
I've got it from getmdl.io (it's official google framework). I can do it, but tomorrow. It's too late here)

**Comment by BrunnerLivio** [comment]
Good!

I suggest a snippet name like `md-box-shadow-Xdp`. Would be nice if you can implement it like this. :)

**Comment by GriNAME** [comment]
Maybe just md-shadow-*dp ? Like md-shadow-4dp

**Comment by BrunnerLivio** [comment]
@GriNAME yes maybe a shorter one is better :+1:

**Comment by GriNAME** [comment]
Great! Wait a PR tomorrow))
